# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  # release:
  #   types: [created]
  # push:
  #     branches:
  #       - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Fetch Project Version
      id: maven
      run: |
            {
              echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
            } >> $GITHUB_OUTPUT
    - name: Create Tag
      id: "tag_create"
      run: |
        {
          set -e
          git tag -f ${{steps.maven.outputs.version}}
          git push -f origin ${{steps.maven.outputs.version}}
        }
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
    - name: Generate Github Summary
      id: summary
      run:  |
            {
              echo "### Details "
              echo "| Variable   | Value       |"
              echo "| ---------- | ----------- |"
              echo "| version    | ${{steps.maven.outputs.version}}    |"
              echo "| checksum   | $(sha256sum dubbo/target/dubbo-${{ steps.maven.outputs.version }}*.jar) |"
            } >> $GITHUB_STEP_SUMMARY
    - name: Create Release
      # Uses the create-github-release action
      uses: nekofar/create-github-release@v1
      with:
        # Defines the tag name for the release (e.g., v1.0.0).
        tag: ${{ steps.maven.outputs.version }}

        # (Optional) Files to include in the release
        files: |
          ${{ github.workspace }}/dubbo/target/dubbo-${{steps.maven.outputs.version}}.jar
          ${{ github.workspace }}/dubbo/target/dubbo-${{steps.maven.outputs.version}}-sources.jar

        # (Optional) Defines the title of the release
        title: Release ${{ steps.maven.outputs.version }}

        # (Optional) Allows multiline release notes
        notes: |
          This is the release notes for version ${{ steps.maven.outputs.version }}.

        # (Optional) Set to "true" to create a draft release. Default is "false"
        draft: false

        # (Optional) Set to "true" to create a pre-release. Default is "false"
        prerelease: true

        # (Optional) Set to "true" to mark this release as the latest. Default is "false"
        latest: true

        # (Optional) GitHub token for authentication. Default: ${{ github.token }}. If not provided, it will use the repository's default token
#         token: ${{ github.token }}          

