# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  # release:
  #   types: [created]
  # push:
  #     branches:
  #       - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
    - name: Output Version
      id: env
      run: |
            {
              echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
            } >> $GITHUB_OUTPUT
            {
              echo "### Details "
              echo "| Variable   | Value       |"
              echo "| ---------- | ----------- |"
              echo "| version    | $version    |"
              echo "| checksum   | $(sha256sum dubbo/dubbo-${version}*.jar) |"
            } >> $GITHUB_STEP_SUMMARY
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: ${{steps.env.outputs.version}}
        tag_exists_error: false
        message: "Latest release"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{steps.env.outputs.version}}
        files: |
          dubbo/dubbo-${{steps.env.outputs.version}}.jar
          dubbo/dubbo-${{steps.env.outputs.version}}-sources.jar
        prerelease: true
          

