# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  # release:
  #   types: [created]
  # push:
  #     branches:
  #       - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Fetch Project Version
      id: maven
      run: |
            {
              echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
            } >> $GITHUB_OUTPUT
    - name: Create Tag
      id: "tag_create"
      run: |
        {
          set -e
          git tag -f ${{steps.maven.outputs.version}}
          git push -f origin ${{steps.maven.outputs.version}}
        }
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -DskipTests -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Checksum
      id: checksum
      run:  |
        {
          directory=${{ github.workspace}}/dubbo/target/ 
          echo directory=${directory} >> $GITHUB_OUTPUT
          
          name=dubbo-${{ steps.maven.outputs.version }}
          echo name=${name} >> $GITHUB_OUTPUT
        
          sha256sum="$(sha256sum ${directory}/${name}.jar | awk NF=1)"
          echo ${sha256sum} > ${directory}/${name}.sha256
          echo sha256sum=${sha256sum} >> $GITHUB_OUTPUT
          
        }
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: -|
          ${{ steps.checksum.outputs.directory }}/${{ steps.checksum.outputs.name}}.jar,
          ${{ steps.checksum.outputs.directory }}/${{ steps.checksum.outputs.name}}.jar.sha256,
          ${{ steps.checksum.outputs.directory }}/${{ steps.checksum.outputs.name}}-sources.jar
        allowUpdates: true
        artifactErrorsFailBuild: true
        prerelease: true
        tag: ${{ steps.maven.outputs.version }}

